#!/usr/bin/env python3

# ROS Python client library
import rospy

# String is used for receiving object information from object_position.py
from std_msgs.msg import String

# Marker is used to visualize privacy-sensitive objects in RViz
from visualization_msgs.msg import Marker


class PrivacyMarker:

    def __init__(self):

        # Initialize the ROS node.
        rospy.init_node("privacy_marker")

        # Read the camera ID from the ROS private parameter namespace.
        self.camera_id = rospy.get_param(
            "~camera_id",
            "left"
        )

        # Publisher for RViz visualization markers.
        self.pub = rospy.Publisher(
            f"/privacy_markers_{self.camera_id}",
            Marker,
            queue_size=10
        )

        # Subscribe to the privacy-object map generated by object_position.py.
        rospy.Subscriber(
            f"/privacy_objects_map_{self.camera_id}",
            String,
            self.callback,
            queue_size=10
        )

        # Dictionary that stores a unique RViz marker ID for each tracked object.
        self.marker_ids = {}

        # ID assigned to the next new object.
        self.next_id = 0

        rospy.loginfo(
            "Privacy marker started"
        )

    def get_marker_id(self, name):
        """
        Each unique object key (e.g. "face_3", already including
        the track id from object_position.py) gets one stable
        marker id for its whole lifetime.
        """

        # Check whether this object already has an assigned marker ID.
        if name not in self.marker_ids:

            # Assign the current unused ID to the object.
            self.marker_ids[name] = self.next_id

            # Increment the counter so the next object gets a different ID.
            self.next_id += 1

        # Return the stable marker ID associated with this object.
        return self.marker_ids[name]

    def callback(self, msg):
        """
        Process an incoming privacy-object message.

        Normal message format:

            <name>,<x>,<y>,<z>

        Example:

            face_3,1.25,2.10,0.80

        A DELETE message has the format:

            <name>,DELETE

        Example:

            face_3,DELETE
        """

        # Split the incoming String message at each comma.
        data = msg.data.split(",")

        # At least a name and one additional field are required.
        if len(data) < 2:
            rospy.logwarn(
                "Invalid map object: %s",
                msg.data
            )
            return

        # The first field identifies the tracked object.
        name = data[0]

        # -----------------------------------------------------------
        # object_position.py can now ask for a marker to be
        # explicitly removed ("<name>,DELETE") when a track goes
        # stale, instead of relying on the marker expiring on its
        # own. This mirrors the reliable stale-track handling that
        # already existed in object_position.py.
        # -----------------------------------------------------------
        if len(data) == 2 and data[1] == "DELETE":
            self.delete_marker(name)
            return

        # At least four fields are required.
        if len(data) < 4:
            rospy.logwarn(
                "Invalid map object: %s",
                msg.data
            )
            return

        try:

            # Convert the X and Y coordinates from strings to floats.
            x = float(data[1])
            y = float(data[2])

            # NOTE: object_position.py now derives z from a real
            # depth-camera measurement (back-projected pixel depth,
            # transformed into the map frame) rather than always
            # sending a fixed placeholder height. No change needed
            # here -- this node already just places the marker at
            # whatever (x, y, z) it's given.
            z = float(data[3])

        except ValueError:
            return

        # Get the stable marker ID associated with this object.
        marker_id = self.get_marker_id(name)

        # -----------------------------------------------------------
        # Create the sphere marker
        # -----------------------------------------------------------

        marker = Marker()

        # The marker is displayed in the global "map" coordinate frame.
        marker.header.frame_id = "map"

        # Timestamp the marker message with the current ROS time.
        marker.header.stamp = rospy.Time.now()

        # Namespace used to distinguish object markers from
        # text-label markers.
        marker.ns = "privacy_objects"

        # Assign the stable ID for this tracked object.
        marker.id = marker_id

        # Display the privacy-sensitive object as a sphere.
        marker.type = Marker.SPHERE

        # ADD creates the marker or updates an existing marker with
        # the same namespace and ID.
        marker.action = Marker.ADD

        # -----------------------------------------------------------
        # 0.05s meant the marker vanished almost immediately
        # unless a fresh position arrived faster than 20 Hz, causing
        # constant flicker. Markers are now persistent (lifetime=0)
        # and are removed explicitly via the DELETE message above
        # when object_position.py drops the track -- this is a more
        # reliable "stale marker" mechanism than a very short timer.
        # -----------------------------------------------------------

        # A duration of zero means the marker does not expire.
        marker.lifetime = rospy.Duration(0)

        # Set the object's position in the map frame.
        marker.pose.position.x = x
        marker.pose.position.y = y
        marker.pose.position.z = z

        # Use the identity quaternion because the sphere does not
        # require any particular orientation.
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0

        # -----------------------------------------------------------
        # 0.005 m (5 mm) spheres are effectively invisible at
        # normal RViz zoom levels. Using a size that's actually
        # visible in the map view.
        # -----------------------------------------------------------

        # Set the size of the sphere in meters.
        marker.scale.x = 0.25
        marker.scale.y = 0.25
        marker.scale.z = 0.25

        # Use different colors to distinguish the two cameras.
        # Left camera  -> Red
        # Right camera -> Blue
        if self.camera_id == "left":
            marker.color.r = 1.0
            marker.color.g = 0.0
            marker.color.b = 0.0

        elif self.camera_id == "right":
            marker.color.r = 0.0
            marker.color.g = 0.0
            marker.color.b = 1.0

        # Fully opaque marker.
        marker.color.a = 1.0

        # NOTE: Marker.text is only rendered for TEXT_VIEW_FACING
        # markers, not SPHERE markers, so it has no visible effect
        # here. Left in for anyone inspecting the message on the
        # topic; add a second TEXT_VIEW_FACING marker if an on-screen
        # label is wanted.
        #marker.text = name

        # Publish the sphere marker to RViz.
        self.pub.publish(marker)

        # -----------------------------------------------------------
        # Text label above the marker
        # -----------------------------------------------------------
        text_marker = Marker()

        # Display the text in the same map coordinate frame.
        text_marker.header.frame_id = "map"
        text_marker.header.stamp = rospy.Time.now()

        # Use a separate namespace so the text marker does not
        # conflict with the sphere marker.
        text_marker.ns = "privacy_labels"

        # Use a different ID namespace, so it doesn't conflict
        # with the sphere marker.
        text_marker.id = marker_id

        # TEXT_VIEW_FACING makes the text automatically face the
        # viewer in RViz.
        text_marker.type = Marker.TEXT_VIEW_FACING

        # ADD creates or updates the text marker.
        text_marker.action = Marker.ADD

        # Place the label slightly above the sphere.
        text_marker.pose.position.x = x
        text_marker.pose.position.y = y
        text_marker.pose.position.z = z + 0.25

        # Text markers also use a quaternion for orientation.
        # The identity quaternion is sufficient here.
        text_marker.pose.orientation.x = 0.0
        text_marker.pose.orientation.y = 0.0
        text_marker.pose.orientation.z = 0.0
        text_marker.pose.orientation.w = 1.0

        # Height of the text in meters
        text_marker.scale.z = 0.12

        # Make the text white.
        text_marker.color.r = 1.0
        text_marker.color.g = 1.0
        text_marker.color.b = 1.0
        text_marker.color.a = 1.0

        # The tracking ID is intentionally omitted from the display
        text_marker.text = "Privacy Sensitive Object: " + name.split("_")[0].capitalize()

        # Keep the text visible until an explicit DELETE message
        text_marker.lifetime = rospy.Duration(0)

        self.pub.publish(text_marker)

    def delete_marker(self, name):
        """
        Remove both the sphere marker and its text label.

        This function is called when object_position.py reports that
        a tracked object is no longer valid.
        """

        # If the object does not have a marker ID, there is nothing
        # to delete.
        if name not in self.marker_ids:
            # Nothing was ever published for this key.
            return

        # Save the ID before deleting the dictionary entry.
        marker_id = self.marker_ids[name]

        # ---------------------------------------------------------
        # Delete sphere marker
        # ---------------------------------------------------------

        marker = Marker()

        marker.header.frame_id = "map"
        marker.header.stamp = rospy.Time.now()

        # Must match the namespace used when the sphere was created.
        marker.ns = "privacy_objects"

        # Must match the original marker ID.
        marker.id = marker_id

        # Tell RViz to remove this marker.
        marker.action = Marker.DELETE

        # Publish the deletion command.
        self.pub.publish(marker)

        # ---------------------------------------------------------
        # Delete text label
        # ---------------------------------------------------------

        text_marker = Marker()

        text_marker.header.frame_id = "map"
        text_marker.header.stamp = rospy.Time.now()

        # Must match the namespace used for the text marker.
        text_marker.ns = "privacy_labels"

        # Use the same ID that was assigned to the original label.
        text_marker.id = marker_id

        # Tell RViz to remove the text marker.
        text_marker.action = Marker.DELETE

        # Publish the deletion command.
        self.pub.publish(text_marker)

        # ---------------------------------------------------------
        # Now remove it from our dictionary
        # ---------------------------------------------------------

        # The object can now receive a new marker ID if it is
        # detected again in the future.
        del self.marker_ids[name]

        rospy.loginfo(
            "Deleted marker: %s (id=%d)",
            name,
            marker_id
        )

if __name__ == "__main__":

    try:

        # Create and initialize the PrivacyMarker node.
        PrivacyMarker()

        # Keep the ROS node running and process callbacks.
        rospy.spin()

    except rospy.ROSInterruptException:

        # Normal shutdown when ROS interrupts the node.
        pass